### PR TITLE
Support new Surface syntax

### PR DESCRIPTION
**Pull request by paulstatezny**

### CODE REVIEW

**Comment by lnr0626** [comment]
@paulstatezny I gave this a try on my codebase and found it doesn't like generator expressions with multiple statements in for blocks. I put up a PR to address the issue, though you may have a better way to do it :-)

**Comment by paulstatezny** [comment]
Thank you @lnr0626 ! Just reviewed your PR. Super helpful having the formatter tested against different codebases to catch things that were missed. 🙌

**Comment by lnr0626** [comment]
I ran into one more bug, but I'm less sure how to fix this one so I'll leave it here. in one of my components, the following:
```
  def render(assigns) do
    ~F"""
    <div class="mx-6 my-4">
      <#slot name="header">
        <h1 :if={@title} class="lg:hidden text-md text-neutral-600 mt-4 mb-2 font-semibold leading-loose tracking-wide">
          {@title}
        </h1>
      </#slot>

      <#slot />
    </div>
    """
  end
```

was formatted to:
```
  def render(assigns) do
    ~F"""
    <div class="mx-6 my-4">
      <#slot name="header">
        <h1
  :if={@title}
  class="lg:hidden text-md text-neutral-600 mt-4 mb-2 font-semibold leading-loose tracking-wide"
>
          {@title}
        </h1>
      </#slot>

      <#slot />
    </div>
    """
  end
```

**Comment by paulstatezny** [comment]
Ahh, thanks @lnr0626. Seems like we're not passing forward the indentation level at some point. I'll add your example as a test case and should be able to isolate the problem area fairly quickly.

**Comment by paulstatezny** [comment]
@lnr0626 I added a test for

```html
<div class="mx-6 my-4">
  <#slot name="header">
    <h1 :if={@title} class="lg:hidden text-md text-neutral-600 mt-4 mb-2 font-semibold leading-loose tracking-wide">
      {@title}
    </h1>
  </#slot>

  <#slot />
</div>
```

was formatted as:

```html
<div class="mx-6 my-4">
  <#slot name="header">
    <h1
      :if={@title}
      class="lg:hidden text-md text-neutral-600 mt-4 mb-2 font-semibold leading-loose tracking-wide"
    >
      {@title}
    </h1>
  </#slot>

  <#slot />
</div>
```

Were you honing in on the `<h1>` opening tag? Was there a paste error in your comment, or did the `:if` and `class` and `>` really get kicked over to the left?

**Comment by paulstatezny** [comment]
@lnr0626 Fixed. 🙂

**Pull request merged**
